USPACE_PREFIX = ../../..
LIBS = drv
BINARY = socket

SOURCES = \
	service.c \
	socket.c \
	tools.c \
	raw_socket.c \
	udp_socket.c \
	tcp_socket.c \
	unix_socket.c \
	common_socket.c

include $(USPACE_PREFIX)/Makefile.common

